# Generated by Django 3.1.1 on 2022-11-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('company', models.CharField(default=None, max_length=255)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('price', models.FloatField(default=None)),
            ],
        ),
    ]
