# Generated by Django 3.1.1 on 2022-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
