# Generated by Django 4.1.3 on 2022-11-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashr', '0002_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
